18130122 Cielo Luz Elena Llamas Servin

18130141 Cristyaquelin Dominguez Felix

18130159 Yañez Gonzalez Christian Emmanuel

Calcular la inversa de A

In [3]:
import numpy as np

A = np.array([[2, 2], [4,6]])
print(f"A = \n{A}")

B = np.linalg.inv(A)
print(f"inv(A) = \n{B}")

A = 
[[2 2]
 [4 6]]
inv(A) = 
[[ 1.5 -0.5]
 [-1.   0.5]]


Calcula AxB, y BxA

In [9]:
import numpy as np

A = np.array([[1, 1], [0, 0]])
print(f"A = \n{A}")

B = np.array([[0, 0], [2, 0]])
print(f"B = \n{B}")

AB = A.dot(B)
print(f"A * B = \n{AB}")
BA = B.dot(A)
print(f"B * A = \n{BA}")

A = 
[[1 1]
 [0 0]]
B = 
[[0 0]
 [2 0]]
A * B = 
[[2 0]
 [0 0]]
B * A = 
[[0 0]
 [2 2]]


Suponemos que A·C=B, Calcular C

In [10]:
"""
C = B / A
"""
import numpy as np

A = np.array([[1, 3], [2, 5]])
print(f"A = \n{A}")

B = np.array([[0, 1], [3, 2]])
print(f"B = \n{B}")

invA = np.linalg.inv(A)
C = invA.dot(B)

print('C=', C, sep='\n')


A = 
[[1 3]
 [2 5]]
B = 
[[0 1]
 [3 2]]
C=
[[ 9.  1.]
 [-3.  0.]]
